config/routes.rb
Rails.application.routes.draw do
  #we call the resources method and pass it a symbol. this instructs Rails to create
  #post routes for creating viewing & deleting instances of Post

#we pass resources :posts to the resources :topics block. This nests the post routes under the topics routes
  resources :topics do
    resources :posts, except: [:index]
  end

#we use `only: []` because we don't want to create any /posts/:id routes, just posts/:post_id/comments
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    #these two lines create POST routes at the URL 'posts/:id/up-vote' and posts/:id/down-vote.
    #the as key-value pairs at the end stipulate the method names which will be associated with these routes: up_vote_path & down_vote_path
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end



  #We create routes for new and create actions. The only hash key will prevent Rails from creating unnecessary routes
  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  #We removed `get "welcome/index"` because we've declared the index view as the root view
  #we also modify the about route (get "welcome/about) to allow users to visit /about rather than /welcome/about
  get 'about' => 'welcome#about'

  get 'welcome/faq'

  root 'welcome#index'

  #sets the users/confirm path to the users confirm#action in the controller
  post 'users/confirm' => 'users#confirm'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def faq
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<h1>About Bloccit</h1>
<div><%= link_to "Follow me", "https://twitter.com/zacharyehren", class: "social-btn" %></div>

app/views/welcome/contact.html.erb
Holler at me!

app/views/welcome/faq.html.erb
What do you call an old snowman?
Water!

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Bloccit</h1>
  <p>Bloccit is a resource for sharing links with your friends!</p>
  <p>
    <%= link_to "Sign In", new_session_path %> or
    <%= link_to "Sign Up", new_user_path, class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row">
  <div class="col-md-4">
     <h2>Solves world hunger</h2>
     <p>Bloccit will deliver food and water to those in need, all over the world.</p>
   </div>
   <div class="col-md-4">
      <h2>Eliminates poverty</h2>
      <p>Bloccit will deliver money and education to those in need, all over the world.</p>
    </div>

   <div class="col-md-4">
     <h2>Turns you into Jeff Goldblum</h2>
     <p>
       Just as our hero slowly turned into a fly in the movie "The Fly", the more you use this Bloccit, the more you'll slowly start turning into Jeff Goldblum.
     </p>
   </div>
 </div>
</div>