config/routes.rb
Rails.application.routes.draw do
  #we call the resources method and pass it a symbol. this instructs Rails to create
  #post routes for creating viewing & deleting instances of Post

#we pass resources :posts to the resources :topics block. This nests the post routes under the topics routes
  resources :topics do
    resources :posts, except: [:index]
  end

#we use `only: []` because we don't want to create any /posts/:id routes, just posts/:post_id/comments
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    #these two lines create POST routes at the URL 'posts/:id/up-vote' and posts/:id/down-vote.
    #the as key-value pairs at the end stipulate the method names which will be associated with these routes: up_vote_path & down_vote_path
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end



  #We create routes for new and create actions. The only hash key will prevent Rails from creating unnecessary routes
  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  #We removed `get "welcome/index"` because we've declared the index view as the root view
  #we also modify the about route (get "welcome/about) to allow users to visit /about rather than /welcome/about
  get 'about' => 'welcome#about'

  get 'welcome/faq'

  root 'welcome#index'

  #sets the users/confirm path to the users confirm#action in the controller
  post 'users/confirm' => 'users#confirm'
end

app/models/post.rb
class Post < ActiveRecord::Base
  #comments are dependent on a post's existence because of the has_many :comments declaration in Post
  #when we delete a post, we also need to delete all related comments. We'll perform a cascade delete, which ensures
  #that when a post is deleted, all of its comments are too
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  after_create :create_vote

#this relates the model and allows us to call post.votes. We all add dependent: :destroy to ensure that votes are destroyed when their parent post is deleted
  has_many :votes, dependent: :destroy

  default_scope { order('rank DESC') }
#we use a lambda (->) to ensure the user is present or signed in. If the user is present, we return all posts. If not, we use the Active Record joins method to retrieve all posts which are public
  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

#we find the up votes for a post by passing value: 1 to where. This fetches a collection of votes with a value of 1.
#This fetches a collection of votes with a value of 1. We then call count on the collection to get a total of all up votes.
  def up_votes
    votes.where(value: 1).count
  end
#same as up_votes but collects all values of -1
  def down_votes
    votes.where(value: -1).count
  end
#we use ActiveRecord's sum method to add the value of all the given post's votes.
#passing :value to sum tells it what attribute to sum in the collection
  def points
    votes.sum(:value)
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end

  private

  def create_vote
    user.votes.create(value: 1, post: self)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
#we use a before_action filter to call the require_sign_in method before each of our controller action, except for show
before_action :require_sign_in, except: :show
#we use a second before_action filter to check the role of a signed-in user. if the current_user isn't authorized based on their role, we'll redirect them to the posts show view
before_action :authorize_user, except: [:show, :new, :create]

  def show
    #we find the post that corresponds to the id in the params we passed to show and assign it to @post
    #unlike the index method, in the show method we populate an instance variable with a single post rather than a collection of posts
    @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    #create an instance variable, @post, then assign it to an empty post returned by Post.new
    @post = Post.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.build(post_params)
#we assign topic to a post
    @post.user = current_user

    #if we successfully save Post to the database, we display a success message
    if @post.save
    #The flash hash provides a way to pass temporary values between actions. Any value placed in flash will be available in the next action and then deleted
      flash[:notice] = "Post was saved."
      #redirecting to post will direc the user to the posts show view using the nested post path
      redirect_to [@topic, @post]
    else
      #if we do not successfully save Post to the database, we display an error message and render the new view again.
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)

    if @post.save
      flash[:notice] = "Post was updated"
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again"
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      flash[:notice] =  "\"#{@post.title}\" was deleted successfully."
      redirect_to @post.topic
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

  private
#this method whitelists the title and body attributes in post to be able to use Mass Assignment
  def post_params
    params.require(:post).permit(:title, :body)
  end

  def authorize_user
    post = Post.find(params[:id])
    unless current_user == post.user || current_user.admin? || current_user.moderator?
      flash[:alert] = "You must be an admin to do that"
      redirect_to [post.topic, post]
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
    def user_is_authorized_for_post?(post)
      current_user && (current_user == post.user || current_user.admin?)
    end

    def user_has_no_posts(post)
       post.count == 0
    end
end

app/views/posts/_form.html.erb
<!-- We use the topic & post local variables we passed into the partial when we rendered it -->
<%= form_for [topic, post] do |f| %>
   <% if post.errors.any? %>
  <!-- if there are any validation errors, we display an alert with the number of errors and their messages -->
     <div class="alert alert-danger">
    <!-- We use the pluralize method to pluralize "error" if there is more than one error -->
    <h4><%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!-- we use form_group_tag to display title errors -->
   <%= form_group_tag(post.errors[:title]) do %>
     <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
   <% end %>
  <!-- we use form_group_tag (from appplication_helper.rb) to display body errors -->
   <%= form_group_tag(post.errors[:body]) do %>
     <%= f.label :body %>
     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
   <% end %>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>

app/views/posts/_post.html.erb
<div class="media">
  <%= render partial: 'votes/voter', locals: { post: post } %>
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to post.title, topic_post_path(post.topic, post) %>
    </h4>
    <small>
      submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
      <%= post.comments.count %> Comments
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <!-- We just replaced a large chunk of code with a partial.
    Partials are fragments of view code, which are called from views.
    Partials are called with the render method. Rendering a partial is like
    copying and pasting view code from another file. -->
    <%= render partial: 'form', locals: { topic: @post.topic, post: @post } %>
    </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned</li>
    </ul>
  </div>
  <div class="col-md-8">
  <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
  </div>
</div>

app/views/posts/show.html.erb
<div>
  <%= render partial: 'votes/voter', locals: { post: @post } %>
  <h1><%= @post.title %></h1> <br />
  <small>submitted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.name %></small>
</div>

<div class="row">
  <div class="col-md-8">
    <p><%= @post.body %></p>
    <div>
      <h3>Comments</h3>
      <!-- This simple line of code will call _comment.html.erb and render all the comments which belong to the given post. -->
      <%= render @post.comments %>
    </div>
    <!-- we all signed in users to see the comment form -->
    <% if current_user %>
    <!-- We render the comment form, and use comments/form because we are rendering the comment form from a post view.
      If we didn't specidy comments, Rails would render the posts form partial by default -->
      <%= render 'comments/form', comment: Comment.new, post: @post %>
    <% end %>
  </div>
  <% if user_is_authorized_for_post?(@post) %>
  <div class="col-md-4">
    <!-- We format a link as an Edit button which directs a user to posts edit page
    edit__topic_post_path(@post) is a helper method that is generated in routes.rb by resources :posts
    edit_topic_post_path takes two arguments, a topic and a post -->
      <%= link_to "Edit", edit_topic_post_path(@post.topic, @post), class: 'btn btn-success' %>
    <!-- We use link_to to create a delete button. The text on button is Delete Post
      We override the default method (:post) with :delete so that when the button is pressed, the route called is the delete route.
      link_to takes an aray of a topic and post which it uses to build the link to delete a nested post.
      The hash confirms the action with a JS confirmation dialog when a user presses the button -->
      <%= link_to "Delete Post", [@post.topic, @post], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'} %>
    </div>
  <% end %>
  <div class="col-md-4">
    <h3>
      <!-- we use the pluralize helper method to display the correctly pluralized forms of point, up vote, and down vote -->
      <%= pluralize(@post.points, 'point') %>
      <div>
        <small>
          <%= pluralize(@post.up_votes, 'up vote') %>
          <%= pluralize(@post.down_votes, 'down vote') %>
        </small>
      </div>
    </h3>
    <% if current_user %>
      <%= render partial: 'favorites/favorite', locals: { post: @post } %>
    <% end %> 
  </div>
</div>